development:
  adapter: sqlite3
  encoding: utf8
  database: nerdvestor_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: sqlite3
  encoding: utf8
  database: nerdvestor_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: nerdvestor_production
  pool: 5
  username: 
  password: